---

- name: Ensure that the application file permissions are set properly
  file: path={{ project_path }}
        recurse=yes
        owner={{ www_user }}
        group={{ www_group }}
        state=directory
#  notify: restart application

#- name: Make
#  file: path={{ virtualenv_path }}
#        recurse=yes
#        owner={{ www_user }}
#        group={{ www_group }}
#        mode=0774
#        state=directory

